version: '3'

services:
  node:
    image: tzlibre/tzlibre:havana
    container_name: tzlibre_node
    volumes:
      - ./scripts:/scripts
      - ~/.tzlibre-node-betanet:/root/.tzlibre-node
      - ~/.tzlibre-client-betanet:/root/.tzlibre-client
    restart: on-failure
    ports:
      - 0.0.0.0:9732:9732
      - 0.0.0.0:9732:9732/udp
      - 127.0.0.1:8732:8732
    expose:
      - 9732
      - 8732
    command: ["./scripts/node.sh"]
  baker:
    image: tzlibre/tzlibre:havana
    container_name: tzlibre_baker
    volumes:
      - ./scripts:/scripts
      - ~/.tzlibre-node-betanet:/root/.tzlibre-node:ro
      - ~/.tzlibre-client-betanet:/root/.tzlibre-client
    command: ["./scripts/baker.sh"]
    stdin_open: true
    tty: true
  endorser:
    image: tzlibre/tzlibre:havana
    container_name: tzlibre_endorser
    volumes:
      - ./scripts:/scripts
      - ~/.tzlibre-node-betanet:/root/.tzlibre-node:ro
      - ~/.tzlibre-client-betanet:/root/.tzlibre-client
    command: ["./scripts/endorser.sh"]
    stdin_open: true
    tty: true
  accuser:
    image: tzlibre/tzlibre:havana
    container_name: tzlibre_accuser
    volumes:
      - ./scripts:/scripts
      - ~/.tzlibre-node-betanet:/root/.tzlibre-node:ro
      - ~/.tzlibre-client-betanet:/root/.tzlibre-client
    command: ["./scripts/accuser.sh"]
    stdin_open: true
    tty: true
  status:
    image: tzlibre/check-chain
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts:/scripts
      - ~/.tzlibre-client-betanet:/root/.tzlibre-client
      - ../.git:/.git
    command: ["./scripts/check.sh"]
